import React from 'react';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <a href="/buy" className="text-2xl font-bold text-indigo-600">
            Fluency Loops
          </a>
        </div>
      </header>

      {/* Content */}
      <main className="flex-grow max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms & Conditions</h1>
        <p className="text-gray-600 mb-8">Last Updated: June 16, 2026</p>

        <div className="prose prose-lg max-w-none space-y-6 text-gray-700">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By registering for and using Fluency Loops, a service operated by CodeExpo, you agree to be bound by these 
              Terms and Conditions. If you do not agree to these terms, please do not use our service. Your continued use 
              of the service constitutes acceptance of any modifications to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">2. Service Description</h2>
            <p>
              Fluency Loops provides an AI-powered English learning platform delivered through WhatsApp. Our service includes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Daily personalized English lessons generated by AI</li>
              <li>Voice pronunciation evaluation and feedback</li>
              <li>Progress tracking and streak maintenance</li>
              <li>Weekly performance summaries</li>
              <li>Interactive learning via WhatsApp messaging</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">3. User Registration & Account</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-2">3.1 Registration Requirements</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must be at least 13 years old to use this service</li>
              <li>You must provide accurate and complete registration information</li>
              <li>You must have an active WhatsApp account</li>
              <li>Each user may maintain only one active account</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mb-2 mt-4">3.2 Account Security</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account information and for all activities 
              that occur under your account. You must notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">4. Subscription & Payment Terms</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-2">4.1 Plans & Pricing</h3>
            <p>
              We offer various subscription plans with different durations and features. Pricing is displayed on our 
              purchase page and is subject to change with notice. All payments are processed securely through Razorpay.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-2 mt-4">4.2 Billing</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Subscriptions are billed in advance</li>
              <li>Payment must be completed before service activation</li>
              <li>All prices are in Indian Rupees (INR) unless otherwise stated</li>
              <li>Applicable taxes will be added to the subscription price</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mb-2 mt-4">4.3 Refund Policy</h3>
            <p>
              We offer a 7-day money-back guarantee from the date of purchase if you are not satisfied with our service. 
              To request a refund, contact us at hello@fluencyloops.in with your registration details. Refunds are 
              processed within 7-10 business days. Partial refunds for unused subscription periods are not available.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-2 mt-4">4.4 Promotional Codes</h3>
            <p>
              Promotional codes are offered at our discretion and may have specific terms, expiration dates, and usage 
              limitations. Codes cannot be combined unless explicitly stated.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">5. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the service only for lawful purposes and in accordance with these terms</li>
              <li>Not share your account with others</li>
              <li>Not attempt to circumvent or manipulate the learning system (e.g., streak manipulation)</li>
              <li>Not use automated systems or bots to interact with the service</li>
              <li>Respect WhatsApp's terms of service and community guidelines</li>
              <li>Not harass, abuse, or send inappropriate content through the platform</li>
              <li>Maintain appropriate conduct in all interactions with the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">6. Intellectual Property</h2>
            <p>
              All content, lessons, features, and functionality of Fluency Loops are owned by CodeExpo and are protected 
              by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, sell, 
              or lease any part of our service without explicit written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">7. AI-Generated Content</h2>
            <p>
              Lessons and evaluations are generated using AI technology (OpenAI GPT-4 and Whisper). While we strive for 
              accuracy and quality, AI-generated content may occasionally contain errors or inconsistencies. We do not 
              guarantee the absolute accuracy of all content and recommend using the service as a supplementary learning tool.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">8. Service Availability</h2>
            <p>
              We strive to provide uninterrupted service but cannot guarantee 100% uptime. We reserve the right to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Modify, suspend, or discontinue any aspect of the service at any time</li>
              <li>Perform scheduled maintenance with reasonable notice</li>
              <li>Address technical issues that may cause temporary service interruptions</li>
            </ul>
            <p className="mt-3">
              We are not liable for any losses resulting from service unavailability or technical issues.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">9. Termination</h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-2">9.1 By User</h3>
            <p>
              You may cancel your subscription at any time by contacting us. Your access will continue until the end of 
              your current billing period, after which no further charges will be made.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-2 mt-4">9.2 By CodeExpo</h3>
            <p>
              We reserve the right to suspend or terminate your account if you violate these terms, engage in fraudulent 
              activity, or for any other reason at our sole discretion. In case of termination for violation, no refunds 
              will be provided.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, CodeExpo and Fluency Loops shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred 
              directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your use or inability to use the service</li>
              <li>Any unauthorized access to or use of your data</li>
              <li>Any interruption or cessation of transmission to or from the service</li>
              <li>Any bugs, viruses, or other harmful code transmitted through the service</li>
              <li>Any errors or omissions in content or for any loss or damage incurred as a result of the use of any content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">11. Disclaimer of Warranties</h2>
            <p>
              The service is provided "as is" and "as available" without warranties of any kind, either express or implied, 
              including but not limited to implied warranties of merchantability, fitness for a particular purpose, or 
              non-infringement. We do not warrant that the service will be uninterrupted, secure, or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">12. Third-Party Services</h2>
            <p>
              Our service integrates with third-party platforms (WhatsApp, OpenAI, Razorpay, etc.). We are not responsible 
              for the availability, accuracy, or content of these third-party services. Your use of such services is subject 
              to their respective terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">13. Governing Law</h2>
            <p>
              These Terms and Conditions shall be governed by and construed in accordance with the laws of India. Any 
              disputes arising out of or related to these terms shall be subject to the exclusive jurisdiction of the 
              courts in [Your City/State], India.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">14. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of significant changes via 
              WhatsApp or email. Your continued use of the service after changes constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-3">15. Contact Information</h2>
            <p>
              For questions, concerns, or support regarding these Terms and Conditions, please contact us:
            </p>
            <div className="bg-gray-100 p-4 rounded-lg mt-3">
              <p><strong>Business Name:</strong> CodeExpo</p>
              <p><strong>Product:</strong> Fluency Loops</p>
              <p><strong>Email:</strong> <a href="mailto:hello@fluencyloops.in" className="text-indigo-600 hover:underline">hello@fluencyloops.in</a></p>
            </div>
          </section>

          <section className="border-t pt-6 mt-8">
            <p className="text-sm text-gray-600">
              By using Fluency Loops, you acknowledge that you have read, understood, and agree to be bound by these 
              Terms and Conditions.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
